version: '3'
 
services:

  loris:
    build: ./loris
    volumes:
      - ./content:/usr/local/share/images
      - cache:/var/cache/loris
    ports:
      - "5004:5004"

  nginx:
    build: ./nginx
    volumes:
      - cache:/var/cache/loris
    ports:
      - "8080:80"

volumes:
  content:
    driver: local
  cache:
    driver: local